# Generated by Django 4.2.5 on 2023-10-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_store_alter_consumption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soda',
            name='stores',
            field=models.ManyToManyField(to='main_app.store'),
        ),
    ]
